# 기존 .properties 방식
#  spring.datasource.url=jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
#  spring.datasource.username=sa
#  spring.datasource.password=
#  spring.datasource.driver-class-name=org.h2.Driver
# 위와 같이 .properties 방식의 반복되는 접두사를 .yaml 으로 생성하면 아래처럼 중복없이 사용할 수 있음.
Spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #자동으로 테이블 생성 (에플리케이션 실행 시점에 테이블을 다 지우고 다시 생성)
    properties:
      hibernate:
        #      show_sql: true # System.out을 통해 찍는다.
        format_sql: true
        open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug # logger를 통해 찍는다.
    org.hibernate.type: trace

